name = "ai-family-album-frontend"
compatibility_date = "2024-03-01"

[env.production]
routes = [
  { pattern = "*", zone_name = "your-domain.com" }
]

[[env.production.pages_build_output_dir]]
directory = "dist"